services:
  nginx:
    image: nginx
    restart: always
    working_dir: /var/www/html
    ports:
      - "6060:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d

  web:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./.docker/php/supervisord.conf:/etc/supervisord.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  db:
    image: mysql
    restart: always
    volumes:
      - .db:/var/lib/mysql
      - ./storage/app:/var/export
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}_Rp
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6666:3306"